### ISSUE TITLE
请问开源许可证是什么？

### ISSUE THREAD

**Issue by zrw269113179** [LookThatMonkey/FastAutomationFrame.Diagram#2]

**Comment by LookThatMonkey** [comment]
BSD开源协议（Berkerley&nbsp;Software&nbsp;Distribution）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月2日(周四) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LookThatMonkey/FastAutomationFrame.Diagram] 请问开源许可证是什么？ (#2)




 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
