### ISSUE TITLE
有没有将连线更换为贝塞尔曲线的计划呢？

### ISSUE THREAD

**Issue by Coderyida** [LookThatMonkey/FastAutomationFrame.Diagram#4]
RT。

**Comment by LookThatMonkey** [comment]
可以，今天我找时间改改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月28日(周二) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LookThatMonkey/FastAutomationFrame.Diagram] 有没有将连线更换为贝塞尔曲线的计划呢？ (Issue #4)




 
RT。

**Comment by LookThatMonkey** [comment]
新增样条曲线，贝塞尔曲线
画布添加参数连线样式（直线，正交，样条，贝塞尔）以及张力系数





线条新增控制点，连线样式，是否启用自定义，张力系统

控制点属性分为直接新增，插入；拾取新增插入








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LookThatMonkey/FastAutomationFrame.Diagram"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月28日(星期二) 中午11:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LookThatMonkey/FastAutomationFrame.Diagram] 有没有将连线更换为贝塞尔曲线的计划呢？ (Issue #4)





 
RT。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

fastautomationframe.diagram.zip (1.45M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=62623666ceefd1ce796e0b561e370b1e4e165200590008571b5703515a1a005205501b0201535b1c5355055159540e08535b0e5138283957571142074d43565c57165f0956514b505b07180251565e43570f181c5147390c&t=exs_ftn_download&code=6b6f8791

**Comment by Coderyida** [comment]
感谢大佬高效产出，期待push后可观摩学习。

**Comment by LookThatMonkey** [comment]
附件中有源码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月2日(周四) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LookThatMonkey/FastAutomationFrame.Diagram] 有没有将连线更换为贝塞尔曲线的计划呢？ (Issue #4)




  
新增样条曲线，贝塞尔曲线 画布添加参数连线样式（直线，正交，样条，贝塞尔）以及张力系数 线条新增控制点，连线样式，是否启用自定义，张力系统 控制点属性分为直接新增，插入；拾取新增插入
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LookThatMonkey/FastAutomationFrame.Diagram" @.&gt;; 发送时间:&nbsp;2023年2月28日(星期二) 中午11:30 @.&gt;; @.&gt;; 主题:&nbsp;[LookThatMonkey/FastAutomationFrame.Diagram] 有没有将连线更换为贝塞尔曲线的计划呢？ (Issue #4) RT。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 从QQ邮箱发来的超大附件 fastautomationframe.diagram.zip (1.45M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=62623666ceefd1ce796e0b561e370b1e4e165200590008571b5703515a1a005205501b0201535b1c5355055159540e08535b0e5138283957571142074d43565c57165f0956514b505b07180251565e43570f181c5147390c&amp;t=exs_ftn_download&amp;code=6b6f8791
  
感谢大佬高效产出，期待push后可观摩学习。

**Comment by Coderyida** [comment]
感谢！已接收
